workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "GameWorld.xcodeproj"
          XCODE_SCHEME: "GameWorld"
    scripts:
      - name: Run Unit Tests (Debug)
        script: |
          xcodebuild test \
            -workspace "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
            -enableCodeCoverage YES

      - name: Build Debug App for iOS
        script: |
          xcodebuild \
            -workspace "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Debug \
            -archivePath $CM_BUILD_DIR/GameWorld.xcarchive \
            archive
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - anjarharimurti.dev@gmail.com
