workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
          XCODE_PROJECT: "GameWorld.xcodeproj"
          XCODE_SCHEME: "GameWorld"
    scripts:
      - name: Build Debug App for iOS
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=17.6' \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - anjarharimurti.dev@gmail.com
